import { test as base, expect } from '@playwright/test';

export type BookingAccount = {
  firstName: string;
  lastName: string;
  email: string;
  message: string;
};

export type BookingFixtures = {
  bookingAccount: BookingAccount;
};

export const test = base.extend<BookingFixtures>({
  bookingAccount: async ({ }, use) => {
    const account = {
      firstName: process.env.CALENDLY_TEST_FIRST_NAME ?? 'QA',
      lastName: process.env.CALENDLY_TEST_LAST_NAME ?? 'Automation',
      email:
        process.env.CALENDLY_TEST_EMAIL ??
        'qa@example.com',
      message:
        process.env.CALENDLY_TEST_MESSAGE ??
        'Automation QA request for Valtive scheduling, generated by Playwright.',
    };

    await use(account);
  },
});

export { expect };
